name: ${pluginName}
version: ${version}
main: com.willfp.talismans.TalismansPlugin
api-version: "1.20"

folia-supported: true

dependencies:
  - name: Triton
    required: true
    bootstrap: false

  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false


permissions:
  talismans.*:
    description: All talismans permissions
    default: op
    children:
      talismans.command.talismans: true
      talismans.command.give: true
      talismans.command.bag: true
      talismans.command.reload: true
      talismans.fromtable.*: true

  talismans.command.reload:
    description: Allows reloading the config
    default: op
  talismans.command.give:
    description: Allows the use of /talismans give.
    default: op
  talismans.command.bag:
    description: Allows the use of /talismans bag.
    default: true
  talismans.command.talismans:
    description: Allows the use of /talismans
    default: true
  talismans.fromtable.*:
    description: Allows crafting all talismans
    default: true
